language: go

go:
  - 1.10.x

install: go get -v ./...

before_script: chmod +x $TRAVIS_BUILD_DIR/build.sh

script: $TRAVIS_BUILD_DIR/build.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-darwin-386.tar.gz
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-darwin-amd64.tar.gz
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-linux-386.tar.gz
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-linux-amd64.tar.gz
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-linux-arm64.tar.gz
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-linux-arm.tar.gz
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-windows-386.tar.gz
    - $TRAVIS_BUILD_DIR/tar/k8s-ctx-import-windows-amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true